stages:
    - "vault_stage"

job_using_vault:
  stage: "vault_stage"
  variables:
    VAULT_SECRET_ENGINE: "ops"
    VAULT_SECRET_PATH: "production/db/password"
    VAULT_VAR_NAME: "DATABASE_PASSWORD"
    VAULT_ADDRESS: "https://your-gitlab.com"
    VAULT_TOKEN: $VAULT_ID_TOKEN
  script: 
    - export DATABASE_PASSWORD=$(./some_script_to_fetch_var.sh)
    - echo "Use ${DATABASE_PASSWORD} here"
